#!/bin/bash
set -eu

if [ "${DOCKER_TAG}" = "latest" ]; then
  # GILOT_VERSION=$(docker run --rm ${IMAGE_NAME} --version)
  GILOT_VERSION=0.2.0
  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${GILOT_VERSION}
  docker push ${DOCKER_REPO}:${GILOT_VERSION}
fi
